// apps/airport/src/app/ui/breadcrumb.tsx
import { Link, useLocation } from 'react-router-dom';
import { useEffect, useState } from 'react';

export function Breadcrumb() {
  const location = useLocation();
  const [urlSegments, setUrlSegments] = useState<
    { path: string; segment: string }[]
  >([]);

  useEffect(() => {
    const urlSegments = location.pathname.split('/').slice(1);
    setUrlSegments(
      urlSegments.map((segment, index) => {
        const path = `/${urlSegments.slice(0, index + 1).join('/')}`;
        return { path, segment };
      })
    );
  }, []);

  return (
    <nav aria-label="breadcrumb">
      <ol className="breadcrumb">
        {urlSegments.map((urlSegment, index) => (
          <li key={index} className="breadcrumb-item">
            {index + 1 === urlSegments.length ? (
              <span style={{ textTransform: 'capitalize' }}>
                {urlSegment.segment}
              </span>
            ) : (
              <Link
                to={urlSegment.path}
                style={{ textTransform: 'capitalize' }}
              >
                {urlSegment.segment}
              </Link>
            )}
          </li>
        ))}
      </ol>
    </nav>
  );
}

// apps/flight-app/src/app/shared/ui/breadcrumb/breadcrumb.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from "@angular/router";

@Component({
  selector: 'breadcrumb',
  templateUrl: './breadcrumb.component.html',
  styleUrls: [ './breadcrumb.component.css' ]
})
export class BreadcrumbComponent implements OnInit {

  currentUrlSegments: {path: string, segment: string}[] = [];

  constructor(private readonly router: Router) {}

  ngOnInit(): void {
    const currentUrl = this.router.url;
    const urlSegments = currentUrl.split('/').slice(1);
    this.currentUrlSegments = urlSegments
      .map((segment, index) => {
        const path = `/${urlSegments.slice(0, index + 1).join('/')}`;
        return { path, segment };
      });
  }
}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li *ngFor="let segment of currentUrlSegments; let i = index" class="breadcrumb-item" [class.active]="i + 1 === currentUrlSegments.length">
      <a *ngIf="i + 1 !== currentUrlSegments.length; else s" [routerLink]="segment.path">{{segment.segment | titlecase}}</a>
      <ng-template #s>
        {{segment.segment | titlecase}}
      </ng-template>
    </li>
  </ol>
</nav>
